export const SET_APP = "SET_APP";

export const UPDATE_APP_DATA = "UPDATE_APP_DATA";
export const UPDATE_CASE_DATA = "UPDATE_CASE_DATA";
export const UPDATE_DROP_ITEM_DATA = "UPDATE_DROP_ITEM_DATA";
export const UPDATE_ITEM_DATA = "UPDATE_ITEM_DATA";
