export const SET_APP = "SET_APP";

export const UPDATE_ITEM_DATA = "UPDATE_ITEM_DATA";

export const DRAGGABLE_ITEM_REMOVED = "DRAGGABLE_ITEM_REMOVED";
export const DRAGGABLE_ITEM_ADDED = "DRAGGABLE_ITEM_ADDED";
export const DRAGGABLE_ITEM_MOVED = "DRAGGABLE_ITEM_MOVED";

export const DRAGGABLE_DROP_LIST_REMOVED = "DRAGGABLE_DROP_LIST_REMOVED";
export const DRAGGABLE_DROP_LIST_ADDED = "DRAGGABLE_DROP_LIST_ADDED";
export const DRAGGABLE_DROP_LIST_MOVED = "DRAGGABLE_DROP_LIST_MOVED";

export const DRAGGABLE_CASE_LIST_MOVED = "DRAGGABLE_ITEM_MOVED";
